version: '3.8'
services:
  api:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file:
      - docker.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - app_network
    depends_on:
      - pg
    command: >
      sh -c "
        npx prisma generate --schema=./src/prisma/schema.prisma &&
        npx prisma migrate dev --name init --schema=./src/prisma/schema.prisma &&
        npm run start"

  pg:
    image: postgres:14
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Tashkent
      PGTZ: Asia/Tashkent
      PGDATA: /var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - '${DOCKER_POSTGRES_DATA_PATH}:/var/lib/postgresql/data'
      - '${DOCKER_POSTGRES_CONF_PATH}/postgresql.conf:/etc/postgresql/postgresql.conf'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
